#服务端口
server:
  port: 8761
spring:
  application:
    name: tx-manager
  thymeleaf:
    prefix: classpath:/html/
    suffix: .html
#redis
#redis主机地址
  redis:
    host: 192.168.2.168
    hostName: 192.168.2.168
    #redis主机端口
    port: 6379
    #redis链接密码
    password:
    pool:
      maxActive: 10
      maxWait: -1
      maxIdle: 5
      minIdle: 0
      timeout: 0
#业务模块与TxManager之间通讯的最大等待时间（单位：秒）
transaction_netty_delay_time: 3
#业务模块与TxManager之间通讯的心跳时间（单位：秒）
transaction_netty_heart_time: 15
#存储到redis下的数据最大保存时间（单位：秒）
redis_save_max_time: 30
#socket server Socket对外服务端口
socket.port: 9999
# 最大socket连接数
socket.max.connection: 100